# Names:
# Arqavan Tajik
# Ali Amini

# Student Numbers:
# 402170895
# 401170529

# Reference:
# Kenneth C. Louden, Compiler Construction: Principles and Practice, 1st Ed.

FIRST = \
{'AdditiveExpression': ['ID', 'NUM', '-', '+', '('],
 'AdditiveExpressionPrime': ['-', '/', '+', 'EPSILON', '*', '('],
 'AdditiveExpressionZegond': ['-', 'NUM', '+', '('],
 'Addop': ['-', '+'],
 'ArgList': ['ID', 'NUM', '-', '+', '('],
 'ArgListPrime': ['EPSILON', ','],
 'Args': ['ID', 'NUM', '-', 'EPSILON', '+', '('],
 'B': ['<', '==', '[', '=', '-', '/', '+', 'EPSILON', '*', '('],
 'BreakStmt': ['break'],
 'C': ['<', '==', 'EPSILON'],
 'Case': ['case'],
 'CaseList': ['case', 'EPSILON'],
 'CompoundStmt': ['{'],
 'Constant': ['NUM'],
 'D': ['-', 'EPSILON', '+'],
 'Declaration': ['int', 'void'],
 'DeclarationInitial': ['int', 'void'],
 'DeclarationList': ['int', 'EPSILON', 'void'],
 'DeclarationPrime': [';', '[', '(', '='],
 'DefaultOpt': ['default', 'EPSILON'],
 'ElseOpt': ['EPSILON', 'else'],
 'Expression': ['ID', 'NUM', '-', '+', '('],
 'Factor': ['ID', '(', 'NUM'],
 'FactorPrime': ['(', 'EPSILON'],
 'FactorZegond': ['(', 'NUM'],
 'FunDeclarationPrime': ['('],
 'G': ['/', 'EPSILON', '*'],
 'GotoStmt': ['goto'],
 'H': ['<', '==', '=', '-', '/', 'EPSILON', '+', '*'],
 'IdStatementPrime': ['<', '==', '[', ':', '-', '(', '=', ';', '/', '+', '*'],
 'IterationStmt': ['while'],
 'Mulop': ['*', '/'],
 'OtherStmt': ['ID', 'while', 'goto', 'NUM', '{', ';', 'return', 'break', '-', '+', '(', 'switch'],
 'Param': ['int', 'void'],
 'ParamList': ['EPSILON', ','],
 'ParamPrime': ['[', 'EPSILON'],
 'Params': ['int', 'void'],
 'Program': ['int', 'EPSILON', 'void'],
 'Relop': ['<', '=='],
 'ReturnStmt': ['return'],
 'ReturnStmtPrime': ['ID', 'NUM', ';', '-', '+', '('],
 'SignedFactor': ['ID', '-', 'NUM', '+', '('],
 'SignedFactorPrime': ['(', 'EPSILON'],
 'SignedFactorZegond': ['NUM', '-', '+', '('],
 'SimpleExpressionPrime': ['<', '==', '-', '/', '+', 'EPSILON', '*', '('],
 'SimpleExpressionZegond': ['-', 'NUM', '+', '('],
 'Statement': ['ID', 'while', '{', '-', '(', 'switch', 'goto', 'NUM', 'if', ';', 'return', 'break', '+'],
 'StatementList': ['ID', 'while', '{', '-', 'EPSILON', '(', 'switch', 'goto', 'NUM', 'if', ';', 'return', 'break', '+'],
 'SwitchStmt': ['switch'],
 'Term': ['ID', 'NUM', '-', '+', '('],
 'TermPrime': ['/', 'EPSILON', '*', '('],
 'TermZegond': ['-', 'NUM', '+', '('],
 'TypeSpecifier': ['int', 'void'],
 'VarCallPrime': ['[', 'EPSILON', '('],
 'VarDeclArrayPrime': [';', '='],
 'VarDeclarationPrime': [';', '[', '='],
 'VarPrime': ['[', 'EPSILON']}

FOLLOW = \
{'AdditiveExpression': [';', ',', ']', ')'],
 'AdditiveExpressionPrime': ['<', '==', ',', ']', ';', ')'],
 'AdditiveExpressionZegond': ['<', '==', ',', ']', ';', ')'],
 'Addop': ['ID', 'NUM', '-', '+', '('],
 'ArgList': [')'],
 'ArgListPrime': [')'],
 'Args': [')'],
 'B': [';', ',', ']', ')'],
 'BreakStmt': ['{', '(', 'goto', 'NUM', 'case', ';', 'return', '+', 'ID', 'while', '-', 'default', 'switch', 'if', 'break', '}', 'else'],
 'C': [';', ',', ']', ')'],
 'Case': ['}', 'case', 'default'],
 'CaseList': ['default', '}'],
 'CompoundStmt': ['ID', 'while', '{', 'void', '$', '-', '(', 'default', 'switch', 'goto', 'NUM', 'case', 'if', ';', 'return', 'break', 'int', '}', '+', 'else'],
 'Constant': [':'],
 'D': ['<', '==', ',', ']', ';', ')'],
 'Declaration': ['ID', 'while', '{', '$', 'void', '-', '(', 'switch', 'goto', 'NUM', 'if', ';', 'return', 'break', 'int', '}', '+'],
 'DeclarationInitial': ['[', ',', '=', ';', '(', ')'],
 'DeclarationList': ['ID', 'while', '{', '$', '-', '(', 'switch', 'goto', 'NUM', 'if', ';', 'return', 'break', '}', '+'],
 'DeclarationPrime': ['ID', 'while', '{', 'void', '$', '-', '(', 'switch', 'goto', 'NUM', 'if', ';', 'return', 'break', 'int', '}', '+'],
 'DefaultOpt': ['}'],
 'ElseOpt': ['{', '(', 'goto', 'NUM', 'case', ';', 'return', '+', 'ID', 'while', '-', 'default', 'switch', 'if', 'break', '}', 'else'],
 'Expression': [';', ',', ']', ')'],
 'Factor': ['<', '==', '-', ',', ']', ';', '/', '+', '*', ')'],
 'FactorPrime': ['<', '==', '-', ',', ']', ';', '/', '+', '*', ')'],
 'FactorZegond': ['<', '==', '-', ',', ']', ';', '/', '+', '*', ')'],
 'FunDeclarationPrime': ['ID', 'while', '{', 'void', '$', '-', '(', 'switch', 'goto', 'NUM', 'if', ';', 'return', 'break', 'int', '}', '+'],
 'G': ['<', '==', ',', ']', ';', '-', '+', ')'],
 'GotoStmt': ['{', '(', 'goto', 'NUM', 'case', ';', 'return', '+', 'ID', 'while', '-', 'default', 'switch', 'if', 'break', '}', 'else'],
 'H': [';', ',', ']', ')'],
 'IdStatementPrime': ['{', '(', 'goto', 'NUM', 'case', ';', 'return', '+', 'ID', 'while', '-', 'default', 'switch', 'if', 'break', '}', 'else'],
 'IterationStmt': ['{', '(', 'goto', 'NUM', 'case', ';', 'return', '+', 'ID', 'while', '-', 'default', 'switch', 'if', 'break', '}', 'else'],
 'Mulop': ['ID', 'NUM', '-', '+', '('],
 'OtherStmt': ['{', '(', 'goto', 'NUM', 'case', ';', 'return', '+', 'ID', 'while', '-', 'default', 'switch', 'if', 'break', '}', 'else'],
 'Param': [')', ','],
 'ParamList': [')'],
 'ParamPrime': [')', ','],
 'Params': [')'],
 'Program': ['$'],
 'Relop': ['ID', 'NUM', '-', '+', '('],
 'ReturnStmt': ['{', '(', 'goto', 'NUM', 'case', ';', 'return', '+', 'ID', 'while', '-', 'default', 'switch', 'if', 'break', '}', 'else'],
 'ReturnStmtPrime': ['{', '(', 'goto', 'NUM', 'case', ';', 'return', '+', 'ID', 'while', '-', 'default', 'switch', 'if', 'break', '}', 'else'],
 'SignedFactor': ['<', '==', ',', ']', ';', '-', '/', '+', '*', ')'],
 'SignedFactorPrime': ['<', '==', ',', ']', ';', '-', '/', '+', '*', ')'],
 'SignedFactorZegond': ['<', '==', ',', ']', ';', '-', '/', '+', '*', ')'],
 'SimpleExpressionPrime': [';', ',', ']', ')'],
 'SimpleExpressionZegond': [';', ',', ']', ')'],
 'Statement': ['ID', 'while', '{', '-', '(', 'default', 'switch', 'goto', 'NUM', 'case', 'if', ';', 'return', 'break', '}', '+', 'else'],
 'StatementList': ['}', 'case', 'default'],
 'SwitchStmt': ['{', '(', 'goto', 'NUM', 'case', ';', 'return', '+', 'ID', 'while', '-', 'default', 'switch', 'if', 'break', '}', 'else'],
 'Term': ['<', '==', ',', ']', ';', '-', '+', ')'],
 'TermPrime': ['<', '==', ',', ']', ';', '-', '+', ')'],
 'TermZegond': ['<', '==', ',', ']', ';', '-', '+', ')'],
 'TypeSpecifier': ['ID'],
 'VarCallPrime': ['<', '==', '-', ',', ']', ';', '/', '+', '*', ')'],
 'VarDeclArrayPrime': ['ID', 'while', '{', 'void', '$', '-', '(', 'switch', 'goto', 'NUM', 'if', ';', 'return', 'break', 'int', '}', '+'],
 'VarDeclarationPrime': ['ID', 'while', '{', 'void', '$', '-', '(', 'switch', 'goto', 'NUM', 'if', ';', 'return', 'break', 'int', '}', '+'],
 'VarPrime': ['<', '==', '-', ',', ']', ';', '/', '+', '*', ')']}

PREDICT = \
{'AdditiveExpression': {'(': 59, '+': 59, '-': 59, 'ID': 59, 'NUM': 59},
 'AdditiveExpressionPrime': {'(': 60, ')': 60, '*': 60, '+': 60, ',': 60, '-': 60, '/': 60, ';': 60, '<': 60, '==': 60, ']': 60},
 'AdditiveExpressionZegond': {'(': 61, '+': 61, '-': 61, 'NUM': 61},
 'Addop': {'+': 64, '-': 65},
 'ArgList': {'(': 93, '+': 93, '-': 93, 'ID': 93, 'NUM': 93},
 'ArgListPrime': {')': 95, ',': 94},
 'Args': {'(': 91, ')': 92, '+': 91, '-': 91, 'ID': 91, 'NUM': 91},
 'B': {'(': 50, ')': 50, '*': 50, '+': 50, ',': 50, '-': 50, '/': 50, ';': 50, '<': 50, '=': 48, '==': 50, '[': 49, ']': 50},
 'BreakStmt': {'break': 41},
 'C': {')': 56, ',': 56, ';': 56, '<': 55, '==': 55, ']': 56},
 'Case': {'case': 100},
 'CaseList': {'case': 98, 'default': 99, '}': 99},
 'CompoundStmt': {'{': 23},
 'Constant': {'NUM': 101},
 'D': {')': 63, '+': 62, ',': 63, '-': 62, ';': 63, '<': 63, '==': 63, ']': 63},
 'Declaration': {'int': 4, 'void': 4},
 'DeclarationInitial': {'int': 5, 'void': 5},
 'DeclarationList': {'$': 3, '(': 3, '+': 3, '-': 3, ';': 3, 'ID': 3, 'NUM': 3, 'break': 3, 'goto': 3, 'if': 3, 'int': 2, 'return': 3, 'switch': 3, 'void': 2, 'while': 3, '{': 3, '}': 3},
 'DeclarationPrime': {'(': 6, ';': 7, '=': 7, '[': 7},
 'DefaultOpt': {'default': 102, '}': 103},
 'ElseOpt': {'(': 29, '+': 29, '-': 29, ';': 29, 'ID': 29, 'NUM': 29, 'break': 29, 'case': 29, 'default': 29, 'else': 28, 'goto': 29, 'if': 29, 'return': 29, 'switch': 29, 'while': 29, '{': 29, '}': 29},
 'Expression': {'(': 46, '+': 46, '-': 46, 'ID': 47, 'NUM': 46},
 'Factor': {'(': 80, 'ID': 81, 'NUM': 82},
 'FactorPrime': {'(': 87, ')': 88, '*': 88, '+': 88, ',': 88, '-': 88, '/': 88, ';': 88, '<': 88, '==': 88, ']': 88},
 'FactorZegond': {'(': 89, 'NUM': 90},
 'FunDeclarationPrime': {'(': 13},
 'G': {')': 70, '*': 69, '+': 70, ',': 70, '-': 70, '/': 69, ';': 70, '<': 70, '==': 70, ']': 70},
 'GotoStmt': {'goto': 96},
 'H': {')': 52, '*': 52, '+': 52, ',': 52, '-': 52, '/': 52, ';': 52, '<': 52, '=': 51, '==': 52, ']': 52},
 'IdStatementPrime': {'(': 40, '*': 40, '+': 40, '-': 40, '/': 40, ':': 39, ';': 40, '<': 40, '=': 40, '==': 40, '[': 40},
 'IterationStmt': {'while': 42},
 'Mulop': {'*': 71, '/': 72},
 'OtherStmt': {'(': 31, '+': 31, '-': 31, ';': 32, 'ID': 30, 'NUM': 31, 'break': 36, 'goto': 37, 'return': 35, 'switch': 38, 'while': 34, '{': 33},
 'Param': {'int': 20, 'void': 20},
 'ParamList': {')': 19, ',': 18},
 'ParamPrime': {')': 22, ',': 22, '[': 21},
 'Params': {'int': 16, 'void': 17},
 'Program': {'$': 1, 'int': 1, 'void': 1},
 'Relop': {'<': 57, '==': 58},
 'ReturnStmt': {'return': 43},
 'ReturnStmtPrime': {'(': 45, '+': 45, '-': 45, ';': 44, 'ID': 45, 'NUM': 45},
 'SignedFactor': {'(': 75, '+': 73, '-': 74, 'ID': 75, 'NUM': 75},
 'SignedFactorPrime': {'(': 76, ')': 76, '*': 76, '+': 76, ',': 76, '-': 76, '/': 76, ';': 76, '<': 76, '==': 76, ']': 76},
 'SignedFactorZegond': {'(': 79, '+': 77, '-': 78, 'NUM': 79},
 'SimpleExpressionPrime': {'(': 54, ')': 54, '*': 54, '+': 54, ',': 54, '-': 54, '/': 54, ';': 54, '<': 54, '==': 54, ']': 54},
 'SimpleExpressionZegond': {'(': 53, '+': 53, '-': 53, 'NUM': 53},
 'Statement': {'(': 27, '+': 27, '-': 27, ';': 27, 'ID': 27, 'NUM': 27, 'break': 27, 'goto': 27, 'if': 26, 'return': 27, 'switch': 27, 'while': 27, '{': 27},
 'StatementList': {'(': 24, '+': 24, '-': 24, ';': 24, 'ID': 24, 'NUM': 24, 'break': 24, 'case': 25, 'default': 25, 'goto': 24, 'if': 24, 'return': 24, 'switch': 24, 'while': 24, '{': 24, '}': 25},
 'SwitchStmt': {'switch': 97},
 'Term': {'(': 66, '+': 66, '-': 66, 'ID': 66, 'NUM': 66},
 'TermPrime': {'(': 67, ')': 67, '*': 67, '+': 67, ',': 67, '-': 67, '/': 67, ';': 67, '<': 67, '==': 67, ']': 67},
 'TermZegond': {'(': 68, '+': 68, '-': 68, 'NUM': 68},
 'TypeSpecifier': {'int': 14, 'void': 15},
 'VarCallPrime': {'(': 83, ')': 84, '*': 84, '+': 84, ',': 84, '-': 84, '/': 84, ';': 84, '<': 84, '==': 84, '[': 84, ']': 84},
 'VarDeclArrayPrime': {';': 11, '=': 12},
 'VarDeclarationPrime': {';': 8, '=': 10, '[': 9},
 'VarPrime': {')': 86, '*': 86, '+': 86, ',': 86, '-': 86, '/': 86, ';': 86, '<': 86, '==': 86, '[': 85, ']': 86}}


RULES = \
{1: ['DeclarationList'],
 2: ['Declaration', 'DeclarationList'],
 3: ['EPSILON'],
 4: ['DeclarationInitial', 'DeclarationPrime'],
 5: ['TypeSpecifier', 'ID', '#declare_id'], 
 6: ['FunDeclarationPrime'],
 7: ['#check_void_var', 'VarDeclarationPrime'],
 8: [';'],
 9: ['[', 'NUM', '#pnum', ']', '#alloc_array', 'VarDeclArrayPrime'],
 10: ['=', 'Expression', '#init_assign', ';'],
 11: [';'],
 12: ['=', 'Expression', '#init_assign', ';'],
 13: ['(', '#func_start', 'Params', ')', '#end_params', 'CompoundStmt', '#func_end'],
 14: ['int', '#type_int'],
 15: ['void', '#type_void'],
 16: ['int', '#type_int', 'ID', '#declare_id', 'ParamPrime', 'ParamList'], 
 17: ['void', '#type_void'],
 18: [',', 'Param', 'ParamList'],
 19: ['EPSILON'],
 20: ['DeclarationInitial', 'ParamPrime'],
 21: ['[', ']', '#make_array_param'],
 22: ['EPSILON'],
 23: ['{', 'DeclarationList', 'StatementList', '}'],
 24: ['Statement', 'StatementList'],
 25: ['EPSILON'],
 26: ['if', '(', 'Expression', ')', '#save', 'Statement', 'ElseOpt'], 
 27: ['OtherStmt'],
 28: ['else', '#jpf_save', 'Statement', '#jp_end'], 
 29: ['EPSILON', '#jp_end_eps'], 
 30: ['ID', '#pid', 'IdStatementPrime'],
 31: ['SimpleExpressionZegond', '#pop_stmt', ';'],
 32: [';'],
 33: ['CompoundStmt'],
 34: ['IterationStmt'],
 35: ['ReturnStmt'],
 36: ['BreakStmt'],
 37: ['GotoStmt'],
 38: ['SwitchStmt'],
 39: [':', '#def_label', 'Statement'], 
 40: ['B', '#pop_stmt', ';'],
 41: ['break', '#break_jump', ';'],
 42: ['while', '#start_loop', '#label', '(', 'Expression', ')', '#save', 'Statement', '#while_end'], 
 43: ['return', 'ReturnStmtPrime'],
 44: [';', '#return_void'],
 45: ['Expression', '#return_val', ';'],
 46: ['SimpleExpressionZegond'],
 47: ['ID', '#pid', 'B'], 
 48: ['=', '#prep_assign', 'Expression', '#assign'], 
 49: ['[', 'Expression', ']', '#array_idx', 'H'],
 50: ['SimpleExpressionPrime'],
 51: ['=', '#prep_assign', 'Expression', '#assign'],
 52: ['G', 'D', 'C'],
 53: ['AdditiveExpressionZegond', 'C'],
 54: ['AdditiveExpressionPrime', 'C'],
 55: ['Relop', 'AdditiveExpression', '#relop'], 
 56: ['EPSILON'],
 57: ['<', '#set_lt'], 
 58: ['==', '#set_eq'], 
 59: ['Term', 'D'],
 60: ['TermPrime', 'D'],
 61: ['TermZegond', 'D'],
 62: ['Addop', 'Term', '#addop', 'D'], 
 63: ['EPSILON'],
 64: ['+', '#set_add'], 
 65: ['-', '#set_sub'], 
 66: ['SignedFactor', 'G'],
 67: ['SignedFactorPrime', 'G'],
 68: ['SignedFactorZegond', 'G'],
 69: ['Mulop', 'SignedFactor', '#mult', 'G'], 
 70: ['EPSILON'],
 71: ['*', '#set_mult'], 
 72: ['/', '#set_div'], 
 73: ['+', 'Factor', '#pos'],
 74: ['-', 'Factor', '#neg'], 
 75: ['Factor'],
 76: ['FactorPrime'],
 77: ['+', 'Factor', '#pos'],
 78: ['-', 'Factor', '#neg'], 
 79: ['FactorZegond'],
 80: ['(', 'Expression', ')'],
 81: ['ID', '#pid', 'VarCallPrime'], 
 82: ['NUM', '#pnum'], 
 83: ['(', '#mark_call', 'Args', ')', '#call'],
 84: ['VarPrime'],
 85: ['[', 'Expression', ']', '#array_idx'],
 86: ['EPSILON'],
 87: ['(', '#mark_call', 'Args', ')', '#call'],
 88: ['EPSILON'],
 89: ['(', 'Expression', ')'],
 90: ['NUM', '#pnum'], 
 91: ['ArgList'],
 92: ['EPSILON'],
 93: ['Expression', '#param', 'ArgListPrime'], 
 94: [',', 'Expression', '#param', 'ArgListPrime'], 
 95: ['EPSILON'],
 96: ['goto', 'ID', '#goto_jump', ';'],
 97: ['switch', '#start_loop', '(', 'Expression', ')', '#save_switch', '{', 'CaseList', 'DefaultOpt', '}', '#end_switch'],
 98: ['Case', 'CaseList'],
 99: ['EPSILON'],
 100: ['case', 'Constant', ':', '#case_check', 'StatementList'],
 101: ['NUM', '#pnum'], 
 102: ['default', ':', '#default_check', 'StatementList'],
 103: ['EPSILON']}